// Known vendors that send receipts inline (no attachment) — body contains receipt
// Verbatim from streamlit_app/utils/gmail.py KNOWN_INLINE_SENDERS
export const KNOWN_INLINE_SENDERS: string[] = [
  'londondrugs.com',
  'londondrugs.ca',
  'walmart.ca',
  'walmart.com',
  'costco.ca',
  'costco.com',
  'canadiantire.ca',
  'bestbuy.ca',
  'staples.ca',
  'homedepot.ca',
  'homedepot.com',
  'sportchek.ca',
  'thebay.com',
  'winners.ca',
  'marshalls.ca',
  'dollarama.com',
  'safeway.ca',
  'sobeys.ca',
  'nofrills.ca',
  'realcanadiansuperstore.ca',
  'save-on-foods.com',
  'superstore.ca',
  'wholefoodsmarket.com',
  'shoppersdrug.com',
  'shoppersdrugmart.ca',
  'pharmasave.com',
  'rexall.ca',
  'chapters.indigo.ca',
  'amazon.ca',
  'amazon.com',
  'ebay.ca',
  'ebay.com',
  'etsy.com',
  'lego.com',
  'toys-r-us.ca',
  'toysrus.ca',
  'cineplex.com',
  'sportinglife.ca',
  'atmospherecanada.ca',
  'telus.com',
  'shaw.ca',
  'rogers.com',
  'bell.ca',
  'skip.com',
  'ubereats.com',
  'doordash.com',
  'airbnb.com',
  'expedia.ca',
  'booking.com',
  'parkingpanda.com',
  'impark.com',
]

// Known vendors that send invoices — scan FROM these even without invoice keywords
// Verbatim from streamlit_app/utils/gmail.py KNOWN_INVOICE_SENDERS
export const KNOWN_INVOICE_SENDERS: string[] = [
  'marriott.com',
  'telus.com',
  'polarhq.com',
  'amazon.ca',
  'lego.com',
  'bestbuy.ca',
  'staples.ca',
  'canadapost-postescanada.ca',
  'adobe.com',
  'anthropic.com',
  'microsoft.com',
  'dropbox.com',
  'google.com',
  'apple.com',
  'shopify.com',
  'keepa.com',
  'sellerboard.com',
]
